# Convolutional Network

In [1]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), ".."))

In [2]:
from pyldl.activations import ReLU
from pyldl.encapsulations import Sequential
from pyldl.losses import CrossEntropyLoss
from pyldl.modules import Conv1D, Flatten, Linear, MaxPool1D
from pyldl.optimizers import SGD
from pyldl.utils import load_usps

In [3]:
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import numpy as np

## Convolutional Modules

In [5]:
X = np.array([
    [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5]],
    [[6, 6, 6], [7, 7, 7], [8, 8, 8], [9, 9, 9], [10, 10, 10]],
    [[11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15]],
    [[16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19], [20, 20, 20]],
])

conv_module = Conv1D(3, 3, 2, 2)

output = conv_module.forward(X)
print("Convolution: ", output)
print("Output shape: ", output.shape)

delta = 5*np.ones_like(output)
backward_delta_output = conv_module.backward_delta(X, delta)
print("\nDelta backward pass: ", backward_delta_output)
print("Delta original shape: ", delta.shape)
print("Output delta shape: ", backward_delta_output.shape)

Convolution:  [[[ -3.13119185   0.13412703]
  [ -5.44074769   1.19855811]]

 [[ -8.90508145   2.79520473]
  [-11.21463729   3.85963581]]

 [[-14.67897105   5.45628243]
  [-16.98852689   6.52071351]]

 [[-20.45286065   8.11736013]
  [-22.76241649   9.18179121]]]
Output shape:  (4, 2, 2)

Delta backward pass:  [[[ 3  0  0]
  [-1  0 -3]
  [ 3  2 -3]
  [-1  0 -3]
  [ 0  2 -3]]

 [[ 3  0  0]
  [-1  0 -3]
  [ 3  2 -3]
  [-1  0 -3]
  [ 0  2 -3]]

 [[ 3  0  0]
  [-1  0 -3]
  [ 3  2 -3]
  [-1  0 -3]
  [ 0  2 -3]]

 [[ 3  0  0]
  [-1  0 -3]
  [ 3  2 -3]
  [-1  0 -3]
  [ 0  2 -3]]]
Delta original shape:  (4, 2, 2)
Output delta shape:  (4, 5, 3)


In [6]:
X = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]],
    ],
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]],
    ],
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]],
    ]
])

delta = np.ones_like(X)

flatten_module = Flatten()
output = flatten_module.forward(X)
print("Flattened input: ", output)
print("Output shape: ", output.shape)

backward_delta_output = flatten_module.backward_delta(X, delta)
print("\nDelta backward pass: ", backward_delta_output)
print("Delta original shape: ", delta.shape)
print("Output delta shape: ", backward_delta_output.shape)

Flattened input:  [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]
Output shape:  (3, 12)

Delta backward pass:  [[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
Delta original shape:  (3, 3, 2, 2)
Output delta shape:  (3, 3, 2, 2)


In [7]:
X = np.array([
    [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5]],
    [[6, 6, 6], [7, 7, 7], [8, 8, 8], [9, 9, 9], [10, 10, 10]],
    [[11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15]],
    [[16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19], [20, 20, 20]],
])

pool_module = MaxPool1D(3, 2)
output = pool_module.forward(X)
print("Pooled input: ", output)
print("Output shape: ", output.shape)

delta = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]],
    [[16, 17, 18], [19, 20, 21], [22, 23, 24], [25, 26, 27], [28, 29, 30]],
    [[31, 32, 33], [34, 35, 36], [37, 38, 39], [40, 41, 42], [43, 44, 45]],
    [[46, 47, 48], [49, 50, 51], [52, 53, 54], [55, 56, 57], [58, 59, 60]]
])
backward_delta_output = pool_module.backward_delta(X, delta)
print("\nDelta backward pass: ", backward_delta_output)
print("Delta original shape: ", delta.shape)
print("Output delta shape: ", backward_delta_output.shape)

Pooled input:  [[[ 3  3  3]
  [ 5  5  5]]

 [[ 8  8  8]
  [10 10 10]]

 [[13 13 13]
  [15 15 15]]

 [[18 18 18]
  [20 20 20]]]
Output shape:  (4, 2, 3)

Delta backward pass:  [[[ 0  0  0]
  [ 0  0  0]
  [ 7  8  9]
  [ 0  0  0]
  [ 7  8  9]]

 [[ 0  0  0]
  [ 0  0  0]
  [22 23 24]
  [ 0  0  0]
  [22 23 24]]

 [[ 0  0  0]
  [ 0  0  0]
  [37 38 39]
  [ 0  0  0]
  [37 38 39]]

 [[ 0  0  0]
  [ 0  0  0]
  [52 53 54]
  [ 0  0  0]
  [52 53 54]]]
Delta original shape:  (4, 5, 3)
Output delta shape:  (4, 5, 3)


## Dataset and Network

In [ ]:
np.random.seed(0)

In [8]:
X, y = load_usps("../data/USPS_data.txt")
y = y.reshape(-1, 1)

# Min-Max Scaling
x_min = X.min()
x_max = X.max()
X = (X - x_min) / (x_max - x_min)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
network = Sequential(Conv1D(3,1,32,1), MaxPool1D(2,2), Flatten(), Linear(4064,100), ReLU(), Linear(100,10))
loss = CrossEntropyLoss()

## Training the convolutional network

In [10]:
losses = SGD(network, loss, X_train[:,:,np.newaxis], y_train, batch_size=32, gradient_step=1e-4, n_iter=1000)

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]


ValueError: operands could not be broadcast together with shapes (3,1,32) (32,254,32) (3,1,32) 

In [ ]:
plt.plot(losses)
plt.xlabel("Iteration")
plt.ylabel("Loss")
plt.show()