# Multiclass Classification with a neural network

In [1]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), ".."))

In [2]:
from pyldl.activations import Sigmoid, Softmax
from pyldl.layers import Sequential
from pyldl.losses import CrossEntropyLoss
from pyldl.modules import Linear
from pyldl.optimizers import SGD
from pyldl.utils import encode_one_hot

In [3]:
import numpy as np

y_one_hot = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
yhat = np.array([[0.1, 0.6, 0.3], [0.3, 0.2, 0.5], [0.2, 0.1, 0.7]])
print(CrossEntropyLoss().forward(y_one_hot, yhat))

[[0.51082562]
 [1.2039728 ]
 [0.35667494]]


## Dataset and Network

In [4]:
from sklearn.datasets import load_digits

digits = load_digits()

X = digits.data
y = digits.target
y_one_hot = encode_one_hot(y)

In [5]:
network = Sequential(Linear(X.shape[1], 128), Sigmoid(), Linear(128, 64), Sigmoid(), Linear(64, 10), Softmax())
loss = CrossEntropyLoss()

## Model performances

In [6]:
SGD(network, loss, X, y_one_hot, batch_size=64, gradient_step=1e-3, n_iter=1000)

In [7]:
def predict(X):
    print(network(X))
    return network(X).argmax(axis=1)

def accuracy(y, yhat):
    return (y == yhat).mean()

yhat = predict(X)
print(f"Accuracy: {accuracy(y, yhat)}")

[[0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]
 [0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]
 [0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]
 ...
 [0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]
 [0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]
 [0.10053631 0.0998624  0.10266182 ... 0.09901552 0.09807798 0.09987327]]
Accuracy: 0.09849749582637729
