In [1]:
import numpy as np
import os
import sys

sys.path.append(os.path.join(os.getcwd(), ".."))

In [2]:
from pyldl.activations import Tanh

tanh = Tanh()
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
from pyldl.losses import CrossEntropyLoss

cross_entropy_loss = CrossEntropyLoss()
y_one_hot = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
yhat = np.array([[0.1, 0.6, 0.3], [0.3, 0.2, 0.5], [0.2, 0.2, 0.6]])
print(cross_entropy_loss(y_one_hot, yhat))

[[0.51082562]
 [1.2039728 ]
 [0.51082562]]


In [4]:
print(cross_entropy_loss.backward(y_one_hot, yhat))

[[-1.66666667]
 [-3.33333333]
 [-1.66666667]]


In [8]:
from pyldl.modules import Linear

linear = Linear(3, 2)
print(linear._parameters, linear._bias)
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(linear(X))

[[0.95875897 0.97604025]
 [0.88627844 0.4951837 ]
 [0.76146535 0.72585724]] [0.05997934 0.59257617]
[[ 5.07569125  4.73655553]
 [12.89519952 11.32779909]
 [20.7147078  17.91904265]]


In [7]:
print(linear.backward_delta([], X))

DimensionMismatchError: Expected dimensions (_, 2), got (3, 3).